<?php

return [
    'courses' => [
        'category_id' => 'Danh mục',
        'title' => 'Tiêu đề',
        'description' => 'Mô tả',
        'content' => 'Nội dung',
        'thumbnail' => 'Ảnh đại diện',
        'price' => 'Giá gốc',
        'sale_price' => 'Giá khuyến mãi',
        'course_type' => 'Loại khóa học',
        'course_format' => 'Hình thức học',
        'total_students' => 'Số học viên',
        'rating' => 'Đánh giá',
        'total_ratings' => 'Tổng đánh giá',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'users' => [
        'id' => 'ID',
        'name' => 'Tên',
        'email' => 'Email',
        'phone' => 'Số điện thoại',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'activity_results' => [
        'id' => 'ID',
        'activity_id' => 'Hoạt động',
        'student_id' => 'Học viên',
        'status' => 'Trạng thái',
        'points' => 'Điểm số',
        'start_time' => 'Thời gian bắt đầu',
        'completed_time' => 'Thời gian hoàn thành',
        'duration' => 'Thời gian làm bài',
        'feedback' => 'Phản hồi',
        'created_at' => 'Ngày tạo',
    ],
    'answers' => [
        'id' => 'ID',
        'question_id' => 'Câu hỏi',
        'answer' => 'Câu trả lời',
        'is_correct' => 'Đáp án đúng',
        'explanation' => 'Giải thích',
        'order_number' => 'Thứ tự',
    ],
    'attendances' => [
        'id' => 'ID',
        'session_id' => 'Buổi học',
        'student_id' => 'Học viên',
        'status' => 'Trạng thái',
        'check_in_time' => 'Thời gian điểm danh',
        'check_out_time' => 'Thời gian kết thúc',
        'remarks' => 'Ghi chú',
        'created_at' => 'Ngày tạo',
    ],
    'banners' => [
        'id' => 'ID',
        'title' => 'Tiêu đề',
        'image' => 'Hình ảnh',
        'mobile_image' => 'Hình ảnh mobile',
        'url' => 'Đường dẫn',
        'position' => 'Vị trí',
        'order' => 'Thứ tự',
        'start_date' => 'Ngày bắt đầu',
        'end_date' => 'Ngày kết thúc',
        'is_active' => 'Trạng thái',
    ],
    'blogs' => [
        'id' => 'ID',
        'user_id' => 'Tác giả',
        'title' => 'Tiêu đề',
        'slug' => 'Đường dẫn',
        'content' => 'Nội dung',
        'thumbnail' => 'Ảnh đại diện',
        'status' => 'Trạng thái',
        'published_at' => 'Ngày xuất bản',
        'views' => 'Lượt xem',
        'likes' => 'Lượt thích',
        'created_at' => 'Ngày tạo',
    ],
    'categories' => [
        'id' => 'ID',
        'name' => 'Tên danh mục',
        'slug' => 'Đường dẫn',
        'description' => 'Mô tả',
        'parent_id' => 'Danh mục cha',
        'order' => 'Thứ tự',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'certificates' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'course_id' => 'Khóa học',
        'certificate_number' => 'Số chứng chỉ',
        'issue_date' => 'Ngày cấp',
        'expiry_date' => 'Ngày hết hạn',
        'status' => 'Trạng thái',
        'grade' => 'Xếp loại',
        'created_at' => 'Ngày tạo',
    ],
    'classes' => [
        'id' => 'ID',
        'name' => 'Tên lớp',
        'code' => 'Mã lớp',
        'course_id' => 'Khóa học',
        'teacher_id' => 'Giảng viên',
        'start_date' => 'Ngày bắt đầu',
        'end_date' => 'Ngày kết thúc',
        'max_students' => 'Số học viên tối đa',
        'current_students' => 'Số học viên hiện tại',
        'status' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'class_schedules' => [
        'id' => 'ID',
        'class_id' => 'Lớp học',
        'day_of_week' => 'Thứ',
        'start_time' => 'Giờ bắt đầu',
        'end_time' => 'Giờ kết thúc',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'class_sessions' => [
        'id' => 'ID',
        'class_id' => 'Lớp học',
        'schedule_id' => 'Lịch học',
        'title' => 'Tiêu đề',
        'description' => 'Mô tả',
        'session_date' => 'Ngày học',
        'start_time' => 'Giờ bắt đầu',
        'end_time' => 'Giờ kết thúc',
        'status' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'class_students' => [
        'id' => 'ID',
        'class_id' => 'Lớp học',
        'student_id' => 'Học viên',
        'status' => 'Trạng thái',
        'enrollment_date' => 'Ngày đăng ký',
        'payment_date' => 'Ngày thanh toán',
        'completion_date' => 'Ngày hoàn thành',
        'created_at' => 'Ngày tạo',
    ],
    'comments' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'commentable_type' => 'Loại bình luận',
        'commentable_id' => 'ID đối tượng',
        'content' => 'Nội dung',
        'parent_id' => 'Bình luận cha',
        'is_approved' => 'Đã duyệt',
        'created_at' => 'Ngày tạo',
    ],
    'employees' => [
        'id' => 'ID',
        'name' => 'Tên',
        'email' => 'Email',
        'phone' => 'Số điện thoại',
        'position' => 'Chức vụ',
        'department' => 'Phòng ban',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'employee_permissions' => [
        'id' => 'ID',
        'name' => 'Tên quyền',
        'slug' => 'Mã quyền',
        'description' => 'Mô tả',
        'module' => 'Module',
        'action' => 'Hành động',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'employee_roles' => [
        'id' => 'ID',
        'name' => 'Tên vai trò',
        'slug' => 'Mã vai trò',
        'description' => 'Mô tả',
        'level' => 'Cấp độ',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'enrollments' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'course_id' => 'Khóa học',
        'status' => 'Trạng thái',
        'progress' => 'Tiến độ',
        'start_date' => 'Ngày bắt đầu',
        'completion_date' => 'Ngày hoàn thành',
        'payment_status' => 'Trạng thái thanh toán',
        'created_at' => 'Ngày tạo',
    ],
    'learning_logs' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'loggable_type' => 'Loại hoạt động',
        'loggable_id' => 'ID đối tượng',
        'action' => 'Hành động',
        'duration_seconds' => 'Thời gian (giây)',
        'action_time' => 'Thời gian thực hiện',
        'created_at' => 'Ngày tạo',
    ],
    'learning_progresses' => [
        'id' => 'ID',
        'student_id' => 'Học viên',
        'total_courses' => 'Tổng khóa học',
        'completed_courses' => 'Khóa học đã hoàn thành',
        'total_lessons' => 'Tổng bài học',
        'completed_lessons' => 'Bài học đã hoàn thành',
        'average_score' => 'Điểm trung bình',
        'learning_time' => 'Thời gian học tập',
        'created_at' => 'Ngày tạo',
    ],
    'lessons' => [
        'id' => 'ID',
        'course_id' => 'Khóa học',
        'title' => 'Tiêu đề',
        'slug' => 'Đường dẫn',
        'description' => 'Mô tả',
        'content' => 'Nội dung',
        'duration' => 'Thời lượng',
        'order' => 'Thứ tự',
        'is_preview' => 'Bài học thử',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'lesson_progresses' => [
        'id' => 'ID',
        'enrollment_id' => 'Đăng ký',
        'lesson_id' => 'Bài học',
        'status' => 'Trạng thái',
        'progress' => 'Tiến độ',
        'time_spent' => 'Thời gian học',
        'completed_at' => 'Ngày hoàn thành',
        'created_at' => 'Ngày tạo',
    ],
    'lesson_videos' => [
        'id' => 'ID',
        'lesson_id' => 'Bài học',
        'title' => 'Tiêu đề',
        'description' => 'Mô tả',
        'video_url' => 'URL video',
        'duration' => 'Thời lượng',
        'order' => 'Thứ tự',
        'is_preview' => 'Video thử',
        'provider' => 'Nhà cung cấp',
        'created_at' => 'Ngày tạo',
    ],
    'notifications' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'title' => 'Tiêu đề',
        'content' => 'Nội dung',
        'type' => 'Loại thông báo',
        'read_at' => 'Đã đọc lúc',
        'is_read' => 'Đã đọc',
        'created_at' => 'Ngày tạo',
    ],
    'online_attendances' => [
        'id' => 'ID',
        'attendance_id' => 'Điểm danh',
        'student_id' => 'Học viên',
        'session_id' => 'Buổi học',
        'join_time' => 'Thời gian tham gia',
        'leave_time' => 'Thời gian rời đi',
        'duration' => 'Thời lượng',
        'created_at' => 'Ngày tạo',
    ],
    'online_attendance_details' => [
        'id' => 'ID',
        'attendance_id' => 'Điểm danh',
        'join_time' => 'Thời gian tham gia',
        'leave_time' => 'Thời gian rời đi',
        'duration_minutes' => 'Thời lượng (phút)',
        'camera_on' => 'Bật camera',
        'microphone_on' => 'Bật microphone',
        'created_at' => 'Ngày tạo',
    ],
    'online_rooms' => [
        'id' => 'ID',
        'session_id' => 'Buổi học',
        'title' => 'Tiêu đề',
        'description' => 'Mô tả',
        'room_id' => 'ID phòng học',
        'provider' => 'Nhà cung cấp',
        'start_time' => 'Thời gian bắt đầu',
        'end_time' => 'Thời gian kết thúc',
        'status' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'online_session_recordings' => [
        'id' => 'ID',
        'online_room_id' => 'Phòng học',
        'title' => 'Tiêu đề',
        'description' => 'Mô tả',
        'recording_url' => 'URL bản ghi',
        'duration' => 'Thời lượng',
        'file_size' => 'Kích thước tệp',
        'status' => 'Trạng thái',
        'view_count' => 'Lượt xem',
        'created_at' => 'Ngày tạo',
    ],
    'orders' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'order_number' => 'Mã đơn hàng',
        'total_amount' => 'Tổng tiền',
        'payment_method' => 'Phương thức thanh toán',
        'payment_status' => 'Trạng thái thanh toán',
        'status' => 'Trạng thái đơn hàng',
        'created_at' => 'Ngày tạo',
    ],
    'order_items' => [
        'id' => 'ID',
        'order_id' => 'Đơn hàng',
        'name' => 'Tên sản phẩm',
        'description' => 'Mô tả',
        'quantity' => 'Số lượng',
        'unit_price' => 'Đơn giá',
        'total_price' => 'Thành tiền',
        'created_at' => 'Ngày tạo',
    ],
    'order_statuses' => [
        'id' => 'ID',
        'name' => 'Tên trạng thái',
        'description' => 'Mô tả',
        'order' => 'Thứ tự',
        'color_code' => 'Mã màu',
        'created_at' => 'Ngày tạo',
    ],
    'permissions' => [
        'id' => 'ID',
        'name' => 'Tên quyền',
        'slug' => 'Mã quyền',
        'description' => 'Mô tả',
        'module' => 'Module',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'progresses' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'progressable_type' => 'Loại tiến độ',
        'progressable_id' => 'ID đối tượng',
        'status' => 'Trạng thái',
        'progress_percentage' => 'Phần trăm tiến độ',
        'completed_at' => 'Ngày hoàn thành',
        'created_at' => 'Ngày tạo',
    ],
    'questions' => [
        'id' => 'ID',
        'test_id' => 'Bài kiểm tra',
        'question' => 'Câu hỏi',
        'type' => 'Loại câu hỏi',
        'points' => 'Điểm',
        'difficulty' => 'Độ khó',
        'order' => 'Thứ tự',
        'is_required' => 'Bắt buộc',
        'created_at' => 'Ngày tạo',
    ],
    'ratings' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'course_id' => 'Khóa học',
        'rating' => 'Điểm đánh giá',
        'comment' => 'Nhận xét',
        'status' => 'Trạng thái',
        'is_featured' => 'Nổi bật',
        'created_at' => 'Ngày tạo',
    ],
    'recording_views' => [
        'id' => 'ID',
        'recording_id' => 'Bản ghi',
        'user_id' => 'Người dùng',
        'view_date' => 'Ngày xem',
        'view_duration' => 'Thời gian xem',
        'progress' => 'Tiến độ',
        'device_type' => 'Loại thiết bị',
        'created_at' => 'Ngày tạo',
    ],
    'resources' => [
        'id' => 'ID',
        'resourceable_type' => 'Loại tài nguyên',
        'resourceable_id' => 'ID đối tượng',
        'title' => 'Tiêu đề',
        'description' => 'Mô tả',
        'type' => 'Loại tệp',
        'file_path' => 'Đường dẫn tệp',
        'file_size' => 'Kích thước tệp',
        'is_public' => 'Công khai',
        'download_count' => 'Lượt tải',
        'created_at' => 'Ngày tạo',
    ],
    'roles' => [
        'id' => 'ID',
        'name' => 'Tên vai trò',
        'slug' => 'Mã vai trò',
        'description' => 'Mô tả',
        'is_system' => 'Vai trò hệ thống',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'session_activities' => [
        'id' => 'ID',
        'session_id' => 'Buổi học',
        'title' => 'Tiêu đề',
        'description' => 'Mô tả',
        'type' => 'Loại hoạt động',
        'status' => 'Trạng thái',
        'start_time' => 'Thời gian bắt đầu',
        'end_time' => 'Thời gian kết thúc',
        'is_required' => 'Bắt buộc',
        'created_at' => 'Ngày tạo',
    ],
    'session_interactions' => [
        'id' => 'ID',
        'session_id' => 'Buổi học',
        'user_id' => 'Người dùng',
        'type' => 'Loại tương tác',
        'content' => 'Nội dung',
        'is_private' => 'Riêng tư',
        'is_highlighted' => 'Nổi bật',
        'is_answered' => 'Đã trả lời',
        'created_at' => 'Ngày tạo',
    ],
    'students' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'code' => 'Mã học viên',
        'name' => 'Họ tên',
        'email' => 'Email',
        'phone' => 'Số điện thoại',
        'status' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'tests' => [
        'id' => 'ID',
        'testable_type' => 'Loại bài kiểm tra',
        'testable_id' => 'ID đối tượng',
        'title' => 'Tiêu đề',
        'description' => 'Mô tả',
        'time_limit' => 'Thời gian làm bài',
        'passing_score' => 'Điểm đạt',
        'max_attempts' => 'Số lần làm tối đa',
        'is_active' => 'Trạng thái',
        'created_at' => 'Ngày tạo',
    ],
    'test_results' => [
        'id' => 'ID',
        'test_id' => 'Bài kiểm tra',
        'user_id' => 'Người dùng',
        'score' => 'Điểm số',
        'time_spent' => 'Thời gian làm bài',
        'status' => 'Trạng thái',
        'is_passed' => 'Đạt',
        'submitted_at' => 'Ngày nộp',
        'created_at' => 'Ngày tạo',
    ],
    'test_result_details' => [
        'id' => 'ID',
        'test_result_id' => 'Kết quả kiểm tra',
        'question_id' => 'Câu hỏi',
        'answer_id' => 'Câu trả lời',
        'text_answer' => 'Câu trả lời văn bản',
        'is_correct' => 'Đúng',
        'score' => 'Điểm',
        'time_spent' => 'Thời gian làm',
        'created_at' => 'Ngày tạo',
    ],
    'video_progresses' => [
        'id' => 'ID',
        'user_id' => 'Người dùng',
        'video_id' => 'Video',
        'current_time' => 'Thời gian hiện tại',
        'completed' => 'Hoàn thành',
        'watch_count' => 'Số lần xem',
        'last_watched_at' => 'Lần xem cuối',
        'created_at' => 'Ngày tạo',
    ],
    'vouchers' => [
        'id' => 'ID',
        'code' => 'Mã giảm giá',
        'sale' => 'Giảm giá',
        'start_date' => 'Ngày bắt đầu',
        'end_date' => 'Ngày kết thúc',
        'usage_count' => 'Số lần sử dụng',
        'max_usage' => 'Số lần sử dụng tối đa',
        'min_order_value' => 'Giá trị đơn hàng tối thiểu',
        'created_at' => 'Ngày tạo',
    ],
];